language: node_js
node_js:
  - 6
  - 7
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
after_script:
  - npm install coveralls
  - npm test -- --coverage
  - cat ./coverage/lcov.info | coveralls
