language: node_js
node_js:
  - 6
  - 7
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run deploy
after_script:
  - npm install coveralls
  - npm test -- --coverage
  - cat ./coverage/lcov.info | coveralls
